## Load libraries

In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import torch

## Define data to build a dataset from

In [2]:
import mltools.dataset as dtools

# Create a simple unbatched dataset
# unbatched_dataset = tf.data.Dataset.from_tensor_slices((tf.random.uniform([100, 2]), tf.random.uniform([100, 2])))
unbatched_dataset = tf.data.Dataset.from_tensor_slices(tf.random.uniform([100, 2]))

# Create a batched dataset
batched_dataset = unbatched_dataset.batch(16)

print(dtools.tf_is_dataset_batched(unbatched_dataset))
print(dtools.tf_is_dataset_batched(batched_dataset))

print(dtools.tf_get_random_element_from_dataset(unbatched_dataset))
print(dtools.tf_get_random_element_from_dataset(batched_dataset))

False
True
tf.Tensor([0.5612968  0.48197746], shape=(2,), dtype=float32)
tf.Tensor([0.98586655 0.10069025], shape=(2,), dtype=float32)


In [3]:
import mltools.dataset as dtools

# Example inputs and labels
length = 120
inputs = np.random.rand(length, 2, 2, 1)  # 100 images of size 32x32x3
labels = np.random.rand(length, 4)  # 100 labels (for a 10-class classification)

splitter_func = dtools.tf_make_datasets_from_tensor_slices
# splitter_func = dtools.tf_make_datasets_from_sklearn_arrays

train_dataset, val_dataset, test_dataset = splitter_func(
    inputs=inputs,
    outputs=labels,
    train_ratio=0.8,
    val_ratio=0.15,
    seed=42,
    batch_size=16,
    avoid_leakage=False,
)

Train size:  96
Validation size:  18
Test size:  6


In [7]:
import mltools.dataset as dtools

# Example inputs and labels
length = 120
inputs = np.random.rand(length, 2, 2, 1)  # 100 images of size 32x32x3
labels = np.random.rand(length, 4)  # 100 labels (for a 10-class classification)

# splitter_func = dtools.tf_make_datasets_from_tensor_slices
splitter_func = dtools.tf_make_datasets_from_sklearn_arrays

train_dataset, val_dataset, test_dataset = splitter_func(
    inputs=inputs,
    outputs=labels,
    train_ratio=0.8,
    val_ratio=0.15,
    seed=42,
    batch_size=None,
    # avoid_leakage=False,
)

print(
    dtools.tf_get_random_element_from_dataset(train_dataset)
)

Train size:  96
Validation size:  16
Test size:  8
(<tf.Tensor: shape=(2, 2, 1), dtype=float64, numpy=
array([[[0.95652186],
        [0.48453802]],

       [[0.59427153],
        [0.06836859]]])>, <tf.Tensor: shape=(4,), dtype=float64, numpy=array([0.28196447, 0.10134534, 0.30883358, 0.37356605])>)


In [8]:
print(
    dtools.tf_are_datasets_leaking(
    dict(
        train = train_dataset,
        val = val_dataset,
        test = test_dataset,
    )
)
)

No data leakage detected between train and val.
No data leakage detected between train and test.
No data leakage detected between val and test.
False
